//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress_CoreMVC.Reports {
    
    public partial class AXGroupTypes : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "DevExpress_CoreMVC.Reports.AXGroupTypes.vsrepx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.GroupFooter1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupFooterBand>("GroupFooter1");
            this.pageInfo2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo2");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");
            this.checkBox40 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox40");
            this.checkBox39 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox39");
            this.checkBox38 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox38");
            this.checkBox37 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox37");
            this.checkBox36 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox36");
            this.checkBox35 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox35");
            this.checkBox34 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox34");
            this.checkBox33 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox33");
            this.checkBox32 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox32");
            this.checkBox31 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox31");
            this.checkBox30 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox30");
            this.checkBox29 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox29");
            this.checkBox28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox28");
            this.checkBox27 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox27");
            this.checkBox26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox26");
            this.checkBox25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox25");
            this.checkBox24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox24");
            this.checkBox23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox23");
            this.checkBox22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox22");
            this.checkBox21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox21");
            this.checkBox20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox20");
            this.checkBox19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox19");
            this.checkBox18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox18");
            this.checkBox17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox17");
            this.checkBox16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox16");
            this.checkBox15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox15");
            this.checkBox14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox14");
            this.checkBox13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox13");
            this.checkBox12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox12");
            this.checkBox11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox11");
            this.checkBox10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox10");
            this.checkBox9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox9");
            this.checkBox8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox8");
            this.checkBox7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox7");
            this.checkBox6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox6");
            this.checkBox5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox5");
            this.checkBox4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox4");
            this.label4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label4");
            this.checkBox3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox3");
            this.checkBox2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox2");
            this.checkBox1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox1");
            this.label3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label3");
            this.label2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label2");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");
            this.tableCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell4");

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");

            // Calculated Fields
            this.PrivilegedRevoked = reportInitializer.GetCalculatedField("PrivilegedRevoked");

            // Styles
            this.GroupDataSub = reportInitializer.GetStyle("GroupDataSub");
            this.Title = reportInitializer.GetStyle("Title");
            this.GroupCaption1 = reportInitializer.GetStyle("GroupCaption1");
            this.PageInfo = reportInitializer.GetStyle("PageInfo");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.GroupFooterBand GroupFooter1;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo2;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox40;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox39;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox38;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox37;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox36;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox35;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox34;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox33;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox32;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox31;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox30;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox29;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox28;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox27;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox26;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox25;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox24;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox23;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox22;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox21;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox20;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox19;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox18;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox17;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox16;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox15;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox14;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox13;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox12;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox11;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox10;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox9;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox8;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox7;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox6;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox5;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox4;
        private DevExpress.XtraReports.UI.XRLabel label4;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox3;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox2;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox1;
        private DevExpress.XtraReports.UI.XRLabel label3;
        private DevExpress.XtraReports.UI.XRLabel label2;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell4;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.UI.XRControlStyle GroupDataSub;
        private DevExpress.XtraReports.UI.XRControlStyle Title;
        private DevExpress.XtraReports.UI.XRControlStyle GroupCaption1;
        private DevExpress.XtraReports.UI.XRControlStyle PageInfo;
        private DevExpress.XtraReports.UI.CalculatedField PrivilegedRevoked;
    }
}
